apiVersion: v1
kind: Service
metadata:
  namespace: {{_ns_}} # the _ns_ context variable gets populated with the namespace name
  name: hello-world
  labels:
    name: hello-world
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: hello-world
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{_ns_}}
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      # comments get stripped out
      containers:
      - name: hello
        image: tutum/hello-world
        ports:
        - containerPort: 80
        env:
        - name: VAR1
          value: "{{var1}}"
        - name: VAR2
          value: "{{var2}}"
        - name: VAR3
          value: "{{var3}}"
        {% if var4 %}
        - name: VAR4
          value: "{{var4}}"
        {% endif %}
        {% if var5 %}
        - name: VAR5
          value: "{{var5}}"
        {% endif %}
